"""
Module 6 — Verification & Reporting
Owner: Elisha

Generates a human-readable integrity report from verification results
and can export the report as a PDF file.
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_integrity_report(
    verification_result: dict,
    center_id: str
) -> str:
    """
    Generate a human-readable integrity report.

    Args:
        verification_result: Dictionary containing verification results.
        center_id: Examination center identifier.

    Returns:
        Formatted report as a string.
    """

    signature_status = (
        "PASS"
        if verification_result.get("signature_valid", False)
        else "FAIL"
    )

    merkle_status = (
        "PASS"
        if verification_result.get("merkle_valid", False)
        else "FAIL"
    )

    audit_status = (
        "PASS"
        if verification_result.get("audit_valid", False)
        else "FAIL"
    )

    overall_status = (
        "PASS"
        if verification_result.get("overall", False)
        else "FAIL"
    )

    report = f"""
========================================
       EXAMSHIELD INTEGRITY REPORT
========================================

Exam Center: {center_id}

Paper Signature Verification : {signature_status}
Answer Merkle Root            : {merkle_status}
Audit Log Verification        : {audit_status}

----------------------------------------
Overall Integrity Status      : {overall_status}
----------------------------------------

This report summarizes the post-exam
integrity verification performed by
ExamShield.
"""

    return report.strip()


def export_report_pdf(
    report_text: str,
    output_path: str
) -> None:
    """
    Export the integrity report as a PDF file.

    Args:
        report_text: Text generated by generate_integrity_report().
        output_path: Destination path for the PDF.
    """

    pdf = canvas.Canvas(
        output_path,
        pagesize=A4
    )

    width, height = A4

    x = 50
    y = height - 50

    pdf.setFont("Helvetica", 11)

    for line in report_text.splitlines():

        if y < 50:
            pdf.showPage()
            pdf.setFont("Helvetica", 11)
            y = height - 50

        pdf.drawString(x, y, line)
        y -= 16

    pdf.save()